<br />
<b>Fatal error</b>:  Uncaught exception 'Zend_Controller_Action_Exception' with message 'Action &quot;error&quot; does not exist and was not trapped in __call()' in D:\xampp\htdocs\localhost\quanstore\library\Zend\Controller\Action.php:485
Stack trace:
#0 D:\xampp\htdocs\localhost\quanstore\library\Zend\Controller\Action.php(518): Zend_Controller_Action-&gt;__call('errorAction', Array)
#1 D:\xampp\htdocs\localhost\quanstore\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action-&gt;dispatch('errorAction')
#2 D:\xampp\htdocs\localhost\quanstore\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 D:\xampp\htdocs\localhost\quanstore\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front-&gt;dispatch()
#4 D:\xampp\htdocs\localhost\quanstore\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap-&gt;run()
#5 D:\xampp\htdocs\localhost\quanstore\index.php(10): Zend_Application-&gt;run()
#6  in <b>D:\xampp\htdocs\localhost\quanstore\library\Zend\Controller\Plugin\Broker.php</b> on line <b>336</b><br />

